/**
 * SEO-focused knowledge-base articles targeting the exact errors and setup
 * questions server owners search for. Each is written from real support
 * cases. Upsert with:  npx tsx database/seed/seed-kb.ts
 *
 * Markdown subset only (see apps/web/components/shared/markdown.tsx):
 * ##/### headings, paragraphs, -/1. lists, **bold**, `code`, fenced blocks,
 * > quotes, [links](/path), --- dividers. No tables/images/HTML.
 */

export interface KbSeedArticle {
  slug: string;
  title: string;
  category: string;
  body: string;
}

export const KB_ARTICLES: KbSeedArticle[] = [
  {
    slug: "minecraft-failed-to-load-datapacks-missing-dimensions",
    title:
      'Fix "Failed to load datapacks" / "No key dimensions in MapLike" Minecraft crash',
    category: "Minecraft",
    body: `Your Minecraft server crashes on startup with something like \`Failed to load datapacks, can't proceed with server load\` or \`No key dimensions in MapLike[{}]\`. This almost always means the **world folder was generated by a different loader, version, or modpack** than the server is currently running.

## Why it happens

Minecraft worlds store references to the datapacks, dimensions and worldgen that created them. When you switch loaders (say Paper to Fabric), change the modpack, or downgrade the game version, the world references content that no longer exists — and the registry fails to load with the errors above.

Common triggers:

- Installing a modpack **on top of an existing world** from a different pack
- Switching the loader (Vanilla/Paper/Fabric/Forge/NeoForge) while keeping the world
- Removing a worldgen/dimension mod (Terralith, William Wurst, Dungeons Arise, etc.) the world was created with
- Downgrading the Minecraft version

## The fix

1. **If you don't need the old world**: delete the \`world\` folder (and \`world_nether\` / \`world_the_end\` if present) in the file manager, then restart. A fresh world generates with the current content. On ReFx, modpack installs offer a **fresh world** option that does this for you.
2. **If you need the old world**: restore the exact loader, version and mod/datapack set the world was created with. The world can only load under the content it references.
3. **If a single datapack is the problem**: remove it from \`world/datapacks/\` and restart.

> Take a backup before deleting anything — on ReFx, an **Essentials backup** captures the world and configs in one click.

## Still crashing?

Check the first \`Caused by:\` line in the crash report. If it names a mod (not a datapack), that mod is missing or incompatible — reinstall it or remove the world's dependency on it. If you're hosting with us, open a ticket and attach the crash report; we read these daily.`,
  },
  {
    slug: "forge-clientside-mod-crash-dedicated-server",
    title:
      'Fix Forge/NeoForge crash: "clientside only mod" or "invalid dist DEDICATED_SERVER"',
    category: "Minecraft",
    body: `Your modded server crashes on boot with \`This mod is for clientside use only\` or \`Attempted to load class ... for invalid dist DEDICATED_SERVER\`. A **client-only mod** is sitting in the server's \`mods/\` folder.

## Why it happens

Mods like shaders, minimaps, FPS optimizers and UI tweaks (OptiFine, Xaero's Minimap, JourneyMap client, Iris, Sodium/Embeddium companions, controller mods…) only work in the game client. A dedicated server has no screen, no renderer and no input — loading a client mod there crashes the JVM immediately.

Modpack authors usually ship ONE mod list for players, so downloading a pack's mods to a server drags the client-only ones along.

## The fix

1. Read the crash report and note the mod it names.
2. Delete that mod's \`.jar\` from the server's \`mods/\` folder (keep it in your own client!).
3. Restart. Repeat if a different client mod is named — packs often carry several.

Typical offenders to remove server-side: \`oculus\`, \`iris\`, \`sodium\`/\`embeddium\` UI companions, \`xaeros_minimap\`, \`journeymap\` (client edition), \`controlling\`, \`toastcontrol\`, \`notenoughanimations\`, \`3dskinlayers\`, \`entityculling\`, shader loaders and resource-pack tooling.

## The lazy (better) fix

Host somewhere that strips client-only mods automatically. ReFx's modpack installer detects known client-only mods during **CurseForge and Modrinth pack installs** and skips them server-side, so packs like Medieval MC boot first try. [See Minecraft hosting plans](/games/minecraft).`,
  },
  {
    slug: "minecraft-server-out-of-memory-xmx-guide",
    title:
      "Minecraft server OutOfMemoryError: how -Xmx, RAM plans and modpacks really interact",
    category: "Minecraft",
    body: `Your server dies with \`java.lang.OutOfMemoryError: Java heap space\`, or the panel shows plenty of RAM while crash reports claim a tiny heap. Here's how Minecraft memory actually works and how to fix each case.

## The three numbers that matter

- **Plan RAM** — what your host allocates to the container/process.
- **-Xmx (max heap)** — what the JVM is ALLOWED to use for game data. Set at launch.
- **Actual usage** — worlds, mobs, chunks, mods. Grows with players and view distance.

The trap: **-Xmx does not automatically match your plan**. If the startup flags say \`-Xmx3G\`, the server uses 3 GB even on a 16 GB plan.

## Diagnosing from a crash report

Open the crash report and find the \`JVM Flags:\` line.

- \`-Xmx3072M\` on a bigger plan → your launch flags are stale. On ReFx the heap is derived from your plan automatically (plan RAM minus a safety headroom for the JVM itself); if you ever see a mismatch, re-save the server's resources and restart.
- **Two** \`-Xmx\` entries → a modpack shipped its own \`user_jvm_args.txt\` overriding yours. Delete or comment the \`-Xmx\`/\`-Xms\` lines in that file — the LAST flag wins. ReFx's pack installer neutralizes these automatically.
- Heap already correct → you genuinely need more memory: reduce view distance and mob caps, prune heavy mods, or upgrade the plan.

## Why you shouldn't set -Xmx equal to ALL your RAM

The JVM needs memory beyond the heap (metaspace, threads, GC structures, netty buffers). Setting \`-Xmx\` to 100% of the container gets the process OOM-killed by the OS instead — same crash, different disguise. Leave 1–2 GB (or ~15%) of headroom; that's exactly what ReFx configures for you.

## Rules of thumb

- Vanilla/Paper, small group: 2–4 GB
- Light modpacks: 4–6 GB
- Heavy packs (ATM, Medieval MC, GregTech): 8–12 GB+

If you're fighting memory on your current host, [our plans](/order) derive the JVM heap from the plan automatically — no flags to maintain.`,
  },
  {
    slug: "install-curseforge-modrinth-modpack-on-server",
    title: "How to install a CurseForge or Modrinth modpack on a Minecraft server",
    category: "Minecraft",
    body: `Installing a modpack on a **server** is not the same as clicking Play in the CurseForge app. This guide covers the manual way and the one-click way.

## What a server install actually needs

1. The correct **loader** (Forge/NeoForge/Fabric/Quilt) at the pack's pinned version
2. The pack's **mods**, minus client-only ones (they crash dedicated servers)
3. The pack's **configs, scripts and datapacks**
4. Sane **JVM flags** that match your RAM, not the pack author's laptop

## Manual install (any host)

1. Download the pack's **server files** if the author publishes them (many CurseForge packs have a "server pack" download). If not, you'll be assembling it from the client pack by hand.
2. Install the loader version pinned by the pack (check \`manifest.json\` or the pack page).
3. Upload \`mods/\`, \`config/\`, \`kubejs/\`/\`scripts/\` and \`defaultconfigs/\` to the server.
4. Delete client-only mods from \`mods/\` (minimaps, shaders, UI mods) — see our [client-mod crash guide](/knowledge-base/forge-clientside-mod-crash-dedicated-server).
5. Check \`user_jvm_args.txt\` doesn't override your memory flags.
6. Start, watch the log, remove whatever crashes, repeat.

Budget 30–60 minutes for a heavy pack the first time.

## One-click install (ReFx)

On ReFx, open your server's **Modpacks** tab and either:

- **Search** CurseForge/Modrinth and click install — we resolve the loader + version, download the server files with retries, strip known client-only mods, neutralize the pack's JVM overrides, and offer a fresh world; or
- **Upload a server pack .zip** — we detect the loader and version from the archive automatically.

Switching packs later? The installer clean-wipes old pack content while preserving your worlds. [Minecraft plans start here](/games/minecraft).`,
  },
  {
    slug: "paper-vs-fabric-vs-forge-vs-neoforge-server",
    title: "Paper vs Fabric vs Forge vs NeoForge: which Minecraft server type to run",
    category: "Minecraft",
    body: `Choosing the server type decides what content you can run and how it performs. The short version:

## Paper — plugins, performance, public servers

Paper (and its forks) is the standard for **plugin** servers: economies, minigames, permissions, anti-cheat. Excellent performance, no client install needed — players join with vanilla. **Can't run mods.** Pick Paper for survival/SMP/community servers where players shouldn't install anything.

## Fabric — light mods, snapshots, performance packs

Fabric is a lightweight **mod** loader with fast updates on new Minecraft versions. Runs performance suites and QoL/content mods; packs like Medieval MC (Fabric) target it. Players need Fabric + the pack installed. Pick Fabric for modded play with a lighter footprint.

## Forge — the big legacy modpacks

Forge carries a decade of mod ecosystem — most classic heavyweight packs (pre-1.20 era especially) are Forge. Heavier than Fabric, slower to update, unmatched back-catalog. Pick Forge when the pack you want is Forge — that's the whole decision.

## NeoForge — Forge's successor

NeoForge is the community fork where most former Forge development happens on modern versions (1.20.2+). New heavyweight packs increasingly target it. Same considerations as Forge, more active maintenance.

## Rules of thumb

- Just friends surviving, no client installs → **Paper**
- A specific modpack → **whatever loader that pack pins** (not negotiable)
- Building a custom modded experience on a modern version → **NeoForge** (or Fabric for lighter scope)

On ReFx you don't commit forever: the Minecraft server has a **loader switcher** — swap Paper/Fabric/Forge/NeoForge (with pinned versions) from the panel, keeping your identity, address and backups. [Start with any loader](/games/minecraft).`,
  },
  {
    slug: "aternos-alternative-when-free-hosting-isnt-enough",
    title: "Aternos alternatives: when free Minecraft hosting stops being worth it",
    category: "Hosting",
    body: `Aternos is genuinely good at what it promises — a free server — and for a weekend world with two friends it's hard to argue with free. This guide is for the moment the trade-offs start costing you players.

## What "free" trades away

- **Queues and cold starts** — the server sleeps when empty; friends wait in line to wake it.
- **Shared, throttled performance** — TPS drops with mods or more than a handful of players.
- **No always-on** — schedules, farms and community servers need the world running when you're not.
- **Limited control** — restricted file access, plugin/mod ceilings, no real backups workflow.

None of that is a scam; it's the price of free. The question is when it's costing more than a few dollars would.

## What paid hosting should actually get you

If you're going to pay, demand ALL of this — it's what we built ReFx around:

- **Always-on, no queue** — the server runs until YOU stop it, with crash auto-restart.
- **Honest resources** — dedicated RAM (no oversell) and burst CPU for startup/chunk-gen spikes.
- **Real tooling** — full file manager and SFTP, one-click CurseForge/Modrinth modpack installs that strip client-only mods, loader switching, scheduled + one-click backups (with offsite storage as an option), console with live players.
- **Transparent pricing** — per-GB pricing with the exact hardware listed, from a few dollars a month.

## Honest advice

- Two friends, occasional evenings, vanilla → stay on free hosting, genuinely.
- Modded, always-on, community, or you're tired of the queue → a small paid plan (4 GB, a few dollars) removes every item above.

Compare for yourself: [our Minecraft plans and pricing](/games/minecraft) are public, and every plan includes the full panel — no feature paywall between "cheap" and "premium".`,
  },
];
