/**
 * Typed field definitions for the Config tab's form view, wired into
 * CONFIG_CATALOG in ./config-files.ts (that file stays the single registry —
 * these are just the data sets, kept here so the catalog stays readable).
 *
 * Rules for authoring:
 * - `key` is the exact key the game writes; Arma array keys drop the `[]`.
 * - `managedByPanel` marks keys the egg re-writes from Startup-tab variables.
 *   Those MUST match the egg's launcher/install script — a key marked wrongly
 *   either lies to the customer or hides a setting they can legitimately edit.
 * - Anything absent from the file renders as "not set — game default"; the
 *   `default` here is only a hint and the value used to prefill "Add".
 */

import type { ConfigFieldMeta } from "./config-files";

/**
 * Arma 3 `server.cfg`. Panel-managed keys come from the egg's refx-run.sh,
 * which rewrites hostname, maxPlayers, password/passwordAdmin (when the
 * Startup variable is set), battleyeLicense and the headless-client allowlist
 * on EVERY boot.
 */
export const ARMA3_SERVER_CFG_FIELDS: ConfigFieldMeta[] = [
  // ---- Identity & access ---------------------------------------------------
  {
    key: "hostname",
    label: "Server name",
    description: "Name shown in the in-game server browser.",
    type: "string",
    group: "Identity & access",
    managedByPanel: true,
  },
  {
    key: "password",
    label: "Join password",
    description: "Required to connect. Empty means anyone can join.",
    type: "password",
    group: "Identity & access",
    managedByPanel: true,
  },
  {
    key: "passwordAdmin",
    label: "Admin password",
    description: "Used with #login to take admin in-game.",
    type: "password",
    group: "Identity & access",
    managedByPanel: true,
  },
  {
    key: "serverCommandPassword",
    label: "Server command password",
    description:
      "Password headless clients and admins use for #exec server commands.",
    type: "password",
    group: "Identity & access",
  },
  {
    key: "maxPlayers",
    label: "Max players",
    description: "Slot count, excluding headless clients.",
    type: "int",
    min: 1,
    max: 256,
    group: "Identity & access",
    managedByPanel: true,
  },
  {
    key: "admins",
    label: "Admin Steam IDs",
    description:
      "SteamID64s granted admin automatically on join — one per line.",
    type: "string[]",
    group: "Identity & access",
  },
  {
    key: "motd",
    label: "Message of the day",
    description: "Lines shown to players after they connect — one per line.",
    type: "string[]",
    group: "Identity & access",
  },
  {
    key: "motdInterval",
    label: "MOTD interval (seconds)",
    description: "Delay between message-of-the-day lines.",
    type: "int",
    min: 0,
    default: "5",
    group: "Identity & access",
  },

  // ---- Gameplay ------------------------------------------------------------
  {
    key: "persistent",
    label: "Persistent mission",
    description: "Keep the mission running after the last player leaves.",
    type: "bool",
    default: "false",
    group: "Gameplay",
  },
  {
    key: "autoSelectMission",
    label: "Auto-select mission",
    description:
      "Start the next mission from the rotation automatically instead of waiting for a vote.",
    type: "bool",
    default: "true",
    group: "Gameplay",
  },
  {
    key: "randomMissionOrder",
    label: "Random mission order",
    description: "Shuffle the mission rotation instead of playing it in order.",
    type: "bool",
    default: "false",
    group: "Gameplay",
  },
  {
    key: "forcedDifficulty",
    label: "Forced difficulty",
    description:
      "Difficulty preset applied to every mission, overriding the mission's own setting.",
    type: "enum",
    options: ["Recruit", "Regular", "Veteran", "Custom"],
    group: "Gameplay",
  },
  {
    key: "missionWhitelist",
    label: "Mission whitelist",
    description:
      "Only these mission .pbo files may be voted/selected — one per line. Empty means all are allowed.",
    type: "string[]",
    group: "Gameplay",
  },
  {
    key: "drawingInMap",
    label: "Allow map drawing",
    description: "Let players draw and place markers on the map.",
    type: "bool",
    default: "true",
    group: "Gameplay",
  },
  {
    key: "allowProfileGlasses",
    label: "Allow profile glasses",
    description: "Let players wear the eyewear chosen in their profile.",
    type: "bool",
    default: "true",
    group: "Gameplay",
  },
  {
    key: "enableDebugConsole",
    label: "Debug console",
    description: "Who may open the in-game debug console.",
    type: "enum",
    options: [
      { value: "0", label: "0 — nobody" },
      { value: "1", label: "1 — logged-in admins" },
      { value: "2", label: "2 — everyone" },
    ],
    default: "0",
    group: "Gameplay",
  },
  {
    key: "zeusCompositionScriptLevel",
    label: "Zeus composition script level",
    description:
      "Script safety level accepted for Zeus compositions — lower is stricter.",
    type: "enum",
    options: [
      { value: "0", label: "0 — no scripts" },
      { value: "1", label: "1 — limited" },
      { value: "2", label: "2 — all scripts" },
    ],
    group: "Gameplay",
    advanced: true,
  },
  {
    key: "skipLobby",
    label: "Skip lobby",
    description:
      "Send players straight into the mission instead of the role-selection lobby.",
    type: "bool",
    group: "Gameplay",
    advanced: true,
  },

  // ---- Security & anti-cheat ----------------------------------------------
  {
    key: "battleyeLicense",
    label: "Accept BattlEye licence",
    description: "Required for BattlEye to run at all.",
    type: "bool",
    group: "Security & anti-cheat",
    managedByPanel: true,
  },
  {
    key: "BattlEye",
    label: "BattlEye anti-cheat",
    description: "Run the BattlEye anti-cheat service.",
    type: "bool",
    default: "true",
    group: "Security & anti-cheat",
  },
  {
    key: "verifySignatures",
    label: "Verify mod signatures",
    description:
      "Reject clients whose mods aren't signed by a key in the server's Keys folder.",
    type: "enum",
    options: [
      { value: "0", label: "0 — off (any mod allowed)" },
      { value: "1", label: "1 — legacy check (deprecated)" },
      { value: "2", label: "2 — full check (recommended)" },
    ],
    default: "2",
    group: "Security & anti-cheat",
  },
  {
    key: "allowedFilePatching",
    label: "Allow file patching",
    description:
      "Whether clients started with -filePatching (loose unpacked files) may connect.",
    type: "enum",
    options: [
      { value: "0", label: "0 — block all file patching" },
      { value: "1", label: "1 — headless clients only" },
      { value: "2", label: "2 — allow everyone" },
    ],
    default: "0",
    group: "Security & anti-cheat",
  },
  {
    key: "filePatchingExceptions",
    label: "File-patching exceptions",
    description:
      "SteamID64s allowed to use -filePatching regardless of the rule above — one per line.",
    type: "string[]",
    group: "Security & anti-cheat",
    advanced: true,
  },
  {
    key: "kickDuplicate",
    label: "Kick duplicate IDs",
    description: "Kick a player whose game ID is already connected.",
    type: "bool",
    default: "true",
    group: "Security & anti-cheat",
  },
  {
    key: "requiredBuild",
    label: "Required client build",
    description:
      "Minimum game build number a client must run — blocks outdated clients.",
    type: "int",
    min: 0,
    group: "Security & anti-cheat",
    advanced: true,
  },
  {
    key: "doubleIdDetected",
    label: "On duplicate ID (script)",
    description: "Server command run when a duplicate player ID is detected.",
    type: "string",
    group: "Security & anti-cheat",
    advanced: true,
  },
  {
    key: "onUserConnected",
    label: "On user connected (script)",
    description: "Server command run when a player connects.",
    type: "string",
    group: "Security & anti-cheat",
    advanced: true,
  },
  {
    key: "onUserDisconnected",
    label: "On user disconnected (script)",
    description: "Server command run when a player disconnects.",
    type: "string",
    group: "Security & anti-cheat",
    advanced: true,
  },
  {
    key: "onHackedData",
    label: "On hacked data (script)",
    description: "Server command run when modified game data is detected.",
    type: "string",
    group: "Security & anti-cheat",
    advanced: true,
  },
  {
    key: "onDifferentData",
    label: "On different data (script)",
    description:
      "Server command run when a client's data differs from the server's.",
    type: "string",
    group: "Security & anti-cheat",
    advanced: true,
  },
  {
    key: "onUnsignedData",
    label: "On unsigned data (script)",
    description: "Server command run when unsigned data is detected.",
    type: "string",
    group: "Security & anti-cheat",
    advanced: true,
  },
  {
    key: "regularCheck",
    label: "Regular check (script)",
    description: "Periodic integrity check command (legacy; usually left off).",
    type: "string",
    group: "Security & anti-cheat",
    advanced: true,
  },

  // ---- Voice (VoN) ---------------------------------------------------------
  {
    key: "disableVoN",
    label: "Disable voice over net",
    description: "Turn off in-game voice entirely.",
    type: "bool",
    default: "false",
    group: "Voice (VoN)",
  },
  {
    key: "vonCodec",
    label: "Voice codec",
    description: "Opus is the modern codec; Speex is the legacy one.",
    type: "enum",
    options: [
      { value: "0", label: "0 — Speex (legacy)" },
      { value: "1", label: "1 — Opus" },
    ],
    default: "1",
    group: "Voice (VoN)",
  },
  {
    key: "vonCodecQuality",
    label: "Voice quality",
    description:
      "Higher is clearer and uses more bandwidth: 0–10 is 8 kHz, 11–20 is 16 kHz, 21–30 is 48 kHz.",
    type: "int",
    min: 0,
    max: 30,
    default: "10",
    group: "Voice (VoN)",
  },

  // ---- Voting --------------------------------------------------------------
  {
    key: "voteThreshold",
    label: "Vote threshold",
    description:
      "Share of connected players needed to pass a vote (0.5 = half). Above 1 disables voting.",
    type: "float",
    min: 0,
    max: 10,
    default: "0.5",
    group: "Voting",
  },
  {
    key: "voteMissionPlayers",
    label: "Players before mission vote",
    description: "Players who must be connected before mission voting starts.",
    type: "int",
    min: 1,
    default: "3",
    group: "Voting",
  },
  {
    key: "votingTimeOut",
    label: "Voting timeout (seconds)",
    description:
      "Time players get to vote on a mission. Some configs use the two-value array form, which the form leaves alone.",
    type: "int",
    min: 0,
    group: "Voting",
    advanced: true,
  },
  {
    key: "roleTimeOut",
    label: "Role selection timeout (seconds)",
    description: "Time players get to pick a role before the mission starts.",
    type: "int",
    min: 0,
    group: "Voting",
    advanced: true,
  },
  {
    key: "briefingTimeOut",
    label: "Briefing timeout (seconds)",
    description: "Time players get on the briefing screen.",
    type: "int",
    min: 0,
    group: "Voting",
    advanced: true,
  },
  {
    key: "debriefingTimeOut",
    label: "Debriefing timeout (seconds)",
    description: "Time players get on the debriefing screen after a mission.",
    type: "int",
    min: 0,
    group: "Voting",
    advanced: true,
  },

  // ---- Network & timeouts --------------------------------------------------
  {
    key: "disconnectTimeout",
    label: "Disconnect timeout (seconds)",
    description:
      "How long a dropped player's slot is held so they can rejoin the same character.",
    type: "int",
    min: 5,
    max: 90,
    default: "90",
    group: "Network & timeouts",
  },
  {
    key: "maxdesync",
    label: "Max desync",
    description: "Desync value above which a player is warned or kicked.",
    type: "int",
    min: 0,
    default: "150",
    group: "Network & timeouts",
  },
  {
    key: "maxping",
    label: "Max ping (ms)",
    description: "Ping above which a player is warned or kicked.",
    type: "int",
    min: 0,
    default: "500",
    group: "Network & timeouts",
  },
  {
    key: "maxpacketloss",
    label: "Max packet loss (%)",
    description: "Packet loss above which a player is warned or kicked.",
    type: "int",
    min: 0,
    max: 100,
    default: "50",
    group: "Network & timeouts",
  },
  {
    key: "kickClientsOnSlowNetwork",
    label: "Kick on slow network",
    description:
      "Actually kick players who exceed the limits above instead of only warning them.",
    type: "bool",
    default: "false",
    group: "Network & timeouts",
  },
  {
    key: "lobbyIdleTimeout",
    label: "Lobby idle timeout (seconds)",
    description:
      "How long the server sits in an idle lobby before restarting the mission.",
    type: "int",
    min: 0,
    default: "300",
    group: "Network & timeouts",
  },
  {
    key: "upnp",
    label: "UPnP port forwarding",
    description:
      "Ask the router to forward ports automatically — not needed on hosted servers.",
    type: "bool",
    default: "false",
    group: "Network & timeouts",
    advanced: true,
  },
  {
    key: "loopback",
    label: "Loopback mode",
    description: "LAN-only mode; the server won't report to the master browser.",
    type: "bool",
    group: "Network & timeouts",
    advanced: true,
  },
  {
    key: "steamProtocolMaxDataSize",
    label: "Steam query packet size",
    description:
      "Maximum size of a Steam query response — raise only if the browser truncates your mod list.",
    type: "int",
    min: 0,
    group: "Network & timeouts",
    advanced: true,
  },

  // ---- Headless clients ----------------------------------------------------
  {
    key: "headlessClients",
    label: "Headless client allowlist",
    description: "IPs allowed to connect as headless clients.",
    type: "string[]",
    group: "Headless clients",
    managedByPanel: true,
  },
  {
    key: "localClient",
    label: "Local client allowlist",
    description:
      "IPs treated as local, so they get unlimited bandwidth (headless clients belong here).",
    type: "string[]",
    group: "Headless clients",
    managedByPanel: true,
  },

  // ---- Logging & maintenance ----------------------------------------------
  {
    key: "timeStampFormat",
    label: "Log timestamp format",
    description: "Timestamp written in front of each server log line.",
    type: "enum",
    options: ["none", "short", "full"],
    default: "none",
    group: "Logging & maintenance",
  },
  {
    key: "logObjectNotFound",
    label: "Log missing objects",
    description: "Write a log line when a mission references a missing object.",
    type: "bool",
    default: "true",
    group: "Logging & maintenance",
  },
  {
    key: "statisticsEnabled",
    label: "Send anonymous statistics",
    description: "Report anonymous usage data to Bohemia Interactive.",
    type: "bool",
    default: "true",
    group: "Logging & maintenance",
  },
  {
    key: "missionsToServerRestart",
    label: "Missions before restart",
    description:
      "Restart the server process after this many missions (-1 disables it).",
    type: "int",
    min: -1,
    group: "Logging & maintenance",
    advanced: true,
  },
  {
    key: "missionsToShutdown",
    label: "Missions before shutdown",
    description:
      "Shut the server down after this many missions (-1 disables it).",
    type: "int",
    min: -1,
    group: "Logging & maintenance",
    advanced: true,
  },
  {
    key: "armaUnitsTimeout",
    label: "Arma Units timeout (seconds)",
    description: "Timeout for Arma Units (units API) requests.",
    type: "int",
    min: 0,
    group: "Logging & maintenance",
    advanced: true,
  },
  {
    key: "enablePlayerDiag",
    label: "Player diagnostics",
    description: "Log extra per-player diagnostic data.",
    type: "bool",
    group: "Logging & maintenance",
    advanced: true,
  },
  {
    key: "callExtReportLimit",
    label: "callExtension report limit (ms)",
    description:
      "Log extension calls that take longer than this many milliseconds.",
    type: "float",
    min: 0,
    group: "Logging & maintenance",
    advanced: true,
  },
  {
    key: "logFile",
    label: "Log file name",
    description: "File the server writes its log to.",
    type: "string",
    group: "Logging & maintenance",
    advanced: true,
  },
];

/**
 * Arma 3 `basic.cfg` — network tuning only. The panel never rewrites this
 * file, and `class sockets { maxPacketSize = ...; };` stays in the raw editor
 * because it's a block, not a key.
 */
export const ARMA3_BASIC_CFG_FIELDS: ConfigFieldMeta[] = [
  {
    key: "MaxMsgSend",
    label: "Max messages per frame",
    description:
      "Messages the server sends per simulation frame. Higher uses more CPU and bandwidth.",
    type: "int",
    min: 1,
    default: "128",
    group: "Bandwidth",
  },
  {
    key: "MaxSizeGuaranteed",
    label: "Max guaranteed packet size (bytes)",
    description:
      "Biggest guaranteed (must-arrive) message, e.g. player commands and shots.",
    type: "int",
    min: 1,
    default: "512",
    group: "Bandwidth",
  },
  {
    key: "MaxSizeNonguaranteed",
    label: "Max non-guaranteed packet size (bytes)",
    description:
      "Biggest droppable message, e.g. position updates. Raising this hurts guaranteed traffic.",
    type: "int",
    min: 1,
    default: "256",
    group: "Bandwidth",
  },
  {
    key: "MinBandwidth",
    label: "Minimum bandwidth (bits/s)",
    description:
      "Bandwidth the server assumes is always available before it starts throttling.",
    type: "int",
    min: 0,
    default: "131072",
    group: "Bandwidth",
  },
  {
    key: "MaxBandwidth",
    label: "Maximum bandwidth (bits/s)",
    description: "Upper limit the server will ever try to use.",
    type: "int",
    min: 0,
    group: "Bandwidth",
  },
  {
    key: "MinErrorToSend",
    label: "Minimum error to send",
    description:
      "How wrong a value must be before an update is sent. Lower is smoother and costs bandwidth.",
    type: "float",
    min: 0,
    default: "0.001",
    group: "Update rate",
  },
  {
    key: "MinErrorToSendNear",
    label: "Minimum error to send (near)",
    description: "Same as above for objects close to the player.",
    type: "float",
    min: 0,
    default: "0.01",
    group: "Update rate",
  },
  {
    key: "MaxCustomFileSize",
    label: "Max custom file size (bytes)",
    description:
      "Largest player-supplied file (face, sound) accepted; 0 means no limit.",
    type: "int",
    min: 0,
    default: "0",
    group: "Update rate",
  },
];

/**
 * BeamMP `ServerConfig.toml` — the egg's launcher rewrites Name, Port,
 * AuthKey, MaxPlayers, MaxCars, Map and Private from Startup variables on
 * every boot; everything below that is the customer's.
 */
export const BEAMMP_SERVER_CONFIG_FIELDS: ConfigFieldMeta[] = [
  {
    key: "Name",
    label: "Server name",
    type: "string",
    description: "Name shown in the BeamMP server list.",
    fileSection: "General",
    group: "General",
    managedByPanel: true,
  },
  {
    key: "MaxPlayers",
    label: "Max players",
    type: "int",
    min: 1,
    fileSection: "General",
    group: "General",
    managedByPanel: true,
  },
  {
    key: "MaxCars",
    label: "Max cars per player",
    type: "int",
    min: 1,
    fileSection: "General",
    group: "General",
    managedByPanel: true,
  },
  {
    key: "Map",
    label: "Map",
    description: "Level path, e.g. /levels/gridmap_v2/info.json.",
    type: "string",
    fileSection: "General",
    group: "General",
    managedByPanel: true,
  },
  {
    key: "Port",
    label: "Port",
    type: "int",
    fileSection: "General",
    group: "General",
    managedByPanel: true,
  },
  {
    key: "AuthKey",
    label: "Auth key",
    description: "BeamMP authentication key that lists the server.",
    type: "password",
    fileSection: "General",
    group: "General",
    managedByPanel: true,
  },
  {
    key: "Private",
    label: "Hide from server list",
    type: "bool",
    fileSection: "General",
    group: "General",
    managedByPanel: true,
  },
  {
    key: "Description",
    label: "Description",
    description: "Blurb shown next to the server in the list.",
    type: "string",
    fileSection: "General",
    group: "Presentation",
  },
  {
    key: "Tags",
    label: "Tags",
    description: "Comma-separated tags used by the server browser's filters.",
    type: "string",
    fileSection: "General",
    group: "Presentation",
  },
  {
    key: "ResourceFolder",
    label: "Resource folder",
    description: "Folder mods are loaded from.",
    type: "string",
    default: "Resources",
    fileSection: "General",
    group: "Advanced",
    advanced: true,
  },
  {
    key: "LogChat",
    label: "Log chat",
    description: "Write player chat to the server console and log.",
    type: "bool",
    default: "true",
    fileSection: "General",
    group: "Advanced",
  },
  {
    key: "Debug",
    label: "Debug logging",
    description: "Verbose logging for troubleshooting.",
    type: "bool",
    default: "false",
    fileSection: "General",
    group: "Advanced",
  },
];

/**
 * Project Zomboid `Zomboid/Server/refx.ini`. The egg seeds this file once and
 * never rewrites it, so only the two ports are panel-managed — they're passed
 * on the command line at every boot and win over whatever the file says.
 */
export const PROJECT_ZOMBOID_INI_FIELDS: ConfigFieldMeta[] = [
  {
    key: "PublicName",
    label: "Server name",
    description: "Name shown in the public server browser.",
    type: "string",
    group: "Listing",
  },
  {
    key: "PublicDescription",
    label: "Description",
    type: "string",
    group: "Listing",
  },
  {
    key: "Public",
    label: "List publicly",
    description: "Advertise the server in the in-game browser.",
    type: "bool",
    default: "true",
    group: "Listing",
  },
  {
    key: "Open",
    label: "Open to everyone",
    description: "Let anyone join without being whitelisted first.",
    type: "bool",
    default: "true",
    group: "Listing",
  },
  {
    key: "Password",
    label: "Join password",
    description: "Password players must enter to connect.",
    type: "password",
    group: "Listing",
  },
  {
    key: "MaxPlayers",
    label: "Max players",
    type: "int",
    min: 1,
    max: 100,
    default: "32",
    group: "Listing",
  },
  {
    key: "ServerWelcomeMessage",
    label: "Welcome message",
    description: "Shown in chat when a player joins.",
    type: "string",
    group: "Listing",
  },
  {
    key: "DefaultPort",
    label: "Game port",
    type: "int",
    group: "Listing",
    managedByPanel: true,
  },
  {
    key: "UDPPort",
    label: "Direct-connect UDP port",
    type: "int",
    group: "Listing",
    managedByPanel: true,
  },
  {
    key: "Mods",
    label: "Mod IDs",
    description: "Semicolon-separated mod IDs loaded at boot.",
    type: "string",
    group: "Mods",
  },
  {
    key: "WorkshopItems",
    label: "Workshop item IDs",
    description: "Semicolon-separated Steam Workshop IDs downloaded at boot.",
    type: "string",
    group: "Mods",
  },
  {
    key: "PVP",
    label: "PvP",
    description: "Allow players to damage each other.",
    type: "bool",
    default: "true",
    group: "Gameplay",
  },
  {
    key: "PauseEmpty",
    label: "Pause when empty",
    description: "Freeze the world while nobody is connected.",
    type: "bool",
    default: "true",
    group: "Gameplay",
  },
  {
    key: "GlobalChat",
    label: "Global chat",
    type: "bool",
    default: "true",
    group: "Gameplay",
  },
  {
    key: "SleepAllowed",
    label: "Sleeping allowed",
    type: "bool",
    default: "false",
    group: "Gameplay",
  },
  {
    key: "SleepNeeded",
    label: "Sleeping needed",
    description: "Players get tired and must sleep.",
    type: "bool",
    default: "false",
    group: "Gameplay",
  },
  {
    key: "KnockedDownAllowed",
    label: "Knock-down allowed",
    type: "bool",
    default: "true",
    group: "Gameplay",
    advanced: true,
  },
  {
    key: "SneakModeHideFromOtherPlayers",
    label: "Sneak hides from players",
    type: "bool",
    default: "true",
    group: "Gameplay",
    advanced: true,
  },
  {
    key: "SpawnPoint",
    label: "Forced spawn point",
    description: "x,y,z coordinates; 0,0,0 lets players choose.",
    type: "string",
    default: "0,0,0",
    group: "Gameplay",
    advanced: true,
  },
  {
    key: "SpawnItems",
    label: "Spawn items",
    description: "Comma-separated item types every player starts with.",
    type: "string",
    group: "Gameplay",
    advanced: true,
  },
  {
    key: "AllowDestructionBySledgehammer",
    label: "Sledgehammer destruction",
    type: "bool",
    default: "true",
    group: "Gameplay",
  },
  {
    key: "SafetySystem",
    label: "PvP safety system",
    description: "Players must disable safety before they can hurt each other.",
    type: "bool",
    default: "true",
    group: "Safety & safehouses",
  },
  {
    key: "SafetyToggleTimer",
    label: "Safety toggle delay (seconds)",
    type: "int",
    min: 0,
    default: "2",
    group: "Safety & safehouses",
    advanced: true,
  },
  {
    key: "PlayerSafehouse",
    label: "Players can claim safehouses",
    type: "bool",
    default: "false",
    group: "Safety & safehouses",
  },
  {
    key: "AdminSafehouse",
    label: "Admin-only safehouses",
    type: "bool",
    default: "false",
    group: "Safety & safehouses",
    advanced: true,
  },
  {
    key: "SafehouseAllowTrepass",
    label: "Allow trespassing",
    type: "bool",
    default: "true",
    group: "Safety & safehouses",
    advanced: true,
  },
  {
    key: "SafehouseAllowFire",
    label: "Allow fire in safehouses",
    type: "bool",
    default: "true",
    group: "Safety & safehouses",
    advanced: true,
  },
  {
    key: "SafehouseAllowLoot",
    label: "Allow looting safehouses",
    type: "bool",
    default: "true",
    group: "Safety & safehouses",
    advanced: true,
  },
  {
    key: "SafehouseDaySurvivedToClaim",
    label: "Days survived to claim",
    type: "int",
    min: 0,
    default: "0",
    group: "Safety & safehouses",
    advanced: true,
  },
  {
    key: "SaveWorldEveryMinutes",
    label: "World save interval (minutes)",
    type: "int",
    min: 0,
    default: "0",
    group: "World & performance",
  },
  {
    key: "MinutesPerPage",
    label: "Minutes per book page",
    type: "float",
    min: 0,
    default: "1.0",
    group: "World & performance",
    advanced: true,
  },
  {
    key: "PingLimit",
    label: "Ping limit (ms)",
    description: "Kick players above this ping; 100 disables the check.",
    type: "int",
    min: 100,
    default: "400",
    group: "World & performance",
  },
  {
    key: "KickFastPlayers",
    label: "Kick fast players",
    description:
      "Anti-cheat speed check — known to false-positive on laggy connections.",
    type: "bool",
    default: "false",
    group: "World & performance",
    advanced: true,
  },
  {
    key: "SpeedLimit",
    label: "Speed limit",
    type: "float",
    min: 10,
    max: 150,
    default: "70.0",
    group: "World & performance",
    advanced: true,
  },
  {
    key: "DisplayUserName",
    label: "Show usernames",
    type: "bool",
    default: "true",
    group: "Players",
  },
  {
    key: "ShowFirstAndLastName",
    label: "Show character names",
    type: "bool",
    default: "false",
    group: "Players",
  },
  {
    key: "AnnounceDeath",
    label: "Announce deaths",
    type: "bool",
    default: "false",
    group: "Players",
  },
  {
    key: "Faction",
    label: "Allow factions",
    type: "bool",
    default: "true",
    group: "Players",
  },
  {
    key: "FactionDaySurvivedToCreate",
    label: "Days survived to create a faction",
    type: "int",
    min: 0,
    default: "0",
    group: "Players",
    advanced: true,
  },
  {
    key: "FactionPlayersRequiredForTag",
    label: "Players required for a faction tag",
    type: "int",
    min: 1,
    default: "1",
    group: "Players",
    advanced: true,
  },
  {
    key: "LoginQueueEnabled",
    label: "Login queue",
    type: "bool",
    default: "false",
    group: "Players",
    advanced: true,
  },
  {
    key: "LoginQueueConnectTimeout",
    label: "Login queue timeout (seconds)",
    type: "int",
    min: 20,
    max: 1200,
    default: "60",
    group: "Players",
    advanced: true,
  },
  {
    key: "VoiceEnable",
    label: "Voice chat",
    type: "bool",
    default: "true",
    group: "Voice",
  },
  {
    key: "Voice3D",
    label: "Positional voice",
    type: "bool",
    default: "true",
    group: "Voice",
  },
  {
    key: "VoiceMinDistance",
    label: "Voice minimum distance",
    type: "float",
    min: 0,
    default: "10.0",
    group: "Voice",
    advanced: true,
  },
  {
    key: "VoiceMaxDistance",
    label: "Voice maximum distance",
    type: "float",
    min: 0,
    default: "100.0",
    group: "Voice",
    advanced: true,
  },
];

/**
 * Minecraft `server.properties`. Every (re)install rewrites `server-port` from
 * the allocation, so that one key is panel-managed.
 */
export const MINECRAFT_PROPERTIES_FIELDS: ConfigFieldMeta[] = [
  {
    key: "motd",
    label: "MOTD",
    description: "Line shown under the server name in the multiplayer list.",
    type: "string",
    default: "A Minecraft Server",
    group: "Listing",
  },
  {
    key: "max-players",
    label: "Max players",
    type: "int",
    min: 0,
    default: "20",
    group: "Listing",
  },
  {
    key: "server-port",
    label: "Server port",
    type: "int",
    group: "Listing",
    managedByPanel: true,
  },
  {
    key: "online-mode",
    label: "Online mode",
    description:
      "Verify players against Mojang's servers. Turning this off lets anyone use any username.",
    type: "bool",
    default: "true",
    group: "Listing",
  },
  {
    key: "white-list",
    label: "Whitelist",
    type: "bool",
    default: "false",
    group: "Listing",
  },
  {
    key: "enforce-whitelist",
    label: "Enforce whitelist",
    description: "Kick players already online who aren't on the whitelist.",
    type: "bool",
    default: "false",
    group: "Listing",
  },
  {
    key: "gamemode",
    label: "Game mode",
    type: "enum",
    options: ["survival", "creative", "adventure", "spectator"],
    default: "survival",
    group: "Gameplay",
  },
  {
    key: "force-gamemode",
    label: "Force game mode",
    description: "Put players back into the default mode when they join.",
    type: "bool",
    default: "false",
    group: "Gameplay",
  },
  {
    key: "difficulty",
    label: "Difficulty",
    type: "enum",
    options: ["peaceful", "easy", "normal", "hard"],
    default: "easy",
    group: "Gameplay",
  },
  {
    key: "hardcore",
    label: "Hardcore",
    description: "Death is permanent — players are set to spectator.",
    type: "bool",
    default: "false",
    group: "Gameplay",
  },
  {
    key: "pvp",
    label: "PvP",
    type: "bool",
    default: "true",
    group: "Gameplay",
  },
  {
    key: "allow-flight",
    label: "Allow flight",
    description: "Permit flight mods rather than kicking for flying.",
    type: "bool",
    default: "false",
    group: "Gameplay",
  },
  {
    key: "allow-nether",
    label: "Allow the Nether",
    type: "bool",
    default: "true",
    group: "Gameplay",
  },
  {
    key: "enable-command-block",
    label: "Enable command blocks",
    type: "bool",
    default: "false",
    group: "Gameplay",
  },
  {
    key: "spawn-protection",
    label: "Spawn protection (blocks)",
    description: "Radius around spawn only operators can build in.",
    type: "int",
    min: 0,
    default: "16",
    group: "World",
  },
  {
    key: "level-name",
    label: "World folder",
    type: "string",
    default: "world",
    group: "World",
  },
  {
    key: "level-seed",
    label: "World seed",
    description: "Only used when the world is generated for the first time.",
    type: "string",
    group: "World",
  },
  {
    key: "level-type",
    label: "World type",
    type: "enum",
    options: [
      "minecraft:normal",
      "minecraft:flat",
      "minecraft:large_biomes",
      "minecraft:amplified",
      "minecraft:single_biome_surface",
    ],
    default: "minecraft:normal",
    group: "World",
    advanced: true,
  },
  {
    key: "generate-structures",
    label: "Generate structures",
    type: "bool",
    default: "true",
    group: "World",
  },
  {
    key: "max-world-size",
    label: "Max world size (blocks)",
    type: "int",
    min: 1,
    max: 29999984,
    default: "29999984",
    group: "World",
    advanced: true,
  },
  {
    key: "spawn-monsters",
    label: "Spawn monsters",
    type: "bool",
    default: "true",
    group: "World",
  },
  {
    key: "view-distance",
    label: "View distance (chunks)",
    description: "The single biggest lever on server CPU and bandwidth.",
    type: "int",
    min: 2,
    max: 32,
    default: "10",
    group: "Performance",
  },
  {
    key: "simulation-distance",
    label: "Simulation distance (chunks)",
    description: "How far from a player entities and blocks keep ticking.",
    type: "int",
    min: 2,
    max: 32,
    default: "10",
    group: "Performance",
  },
  {
    key: "player-idle-timeout",
    label: "Idle timeout (minutes)",
    description: "Kick idle players after this long; 0 never kicks.",
    type: "int",
    min: 0,
    default: "0",
    group: "Performance",
  },
  {
    key: "max-tick-time",
    label: "Max tick time (ms)",
    description:
      "Watchdog limit before the server shuts itself down; -1 disables it.",
    type: "int",
    min: -1,
    default: "60000",
    group: "Performance",
    advanced: true,
  },
  {
    key: "enable-rcon",
    label: "Enable RCON",
    description:
      "Remote console on a separate port. The panel console doesn't need it.",
    type: "bool",
    default: "false",
    group: "Remote access",
    advanced: true,
  },
  {
    key: "rcon.port",
    label: "RCON port",
    type: "int",
    default: "25575",
    group: "Remote access",
    advanced: true,
  },
  {
    key: "rcon.password",
    label: "RCON password",
    type: "password",
    group: "Remote access",
    advanced: true,
  },
  {
    key: "enable-query",
    label: "Enable query",
    description: "GameSpy4 protocol for server-listing sites.",
    type: "bool",
    default: "false",
    group: "Remote access",
    advanced: true,
  },
];
