#!/usr/bin/env bash
# =============================================================================
# ReFx Hosting — Linux node-agent installer
# Supports: Ubuntu, Debian, AlmaLinux, Rocky Linux (systemd + x86_64/aarch64)
#
# Usage:
#   sudo ./install-node.sh --panel-url https://api.refx.example --token <NODE_TOKEN>
#   # or via env:
#   PANEL_URL=... NODE_TOKEN=... sudo ./install-node.sh
#
# The NODE_TOKEN is the bootstrap token shown in the admin panel when you
# create the node (Admin → Nodes → Add). The agent uses it once to register
# and receive its signed configuration.
# =============================================================================
set -euo pipefail

# ---- defaults ---------------------------------------------------------------
PANEL_URL="${PANEL_URL:-}"
NODE_TOKEN="${NODE_TOKEN:-}"
AGENT_VERSION="${AGENT_VERSION:-latest}"
REPO="refxfrank/refxhosting"
INSTALL_DIR="/usr/local/bin"
DATA_DIR="/var/lib/refx"
CONFIG_DIR="/etc/refx"
RUN_USER="refx"
SKIP_DOCKER="${SKIP_DOCKER:-false}"

log()  { printf '\033[1;32m[refx]\033[0m %s\n' "$*"; }
warn() { printf '\033[1;33m[refx]\033[0m %s\n' "$*" >&2; }
die()  { printf '\033[1;31m[refx]\033[0m %s\n' "$*" >&2; exit 1; }

# ---- args -------------------------------------------------------------------
while [[ $# -gt 0 ]]; do
  case "$1" in
    --panel-url) PANEL_URL="$2"; shift 2;;
    --token)     NODE_TOKEN="$2"; shift 2;;
    --version)   AGENT_VERSION="$2"; shift 2;;
    --skip-docker) SKIP_DOCKER=true; shift;;
    -h|--help) grep '^#' "$0" | sed 's/^# \{0,1\}//'; exit 0;;
    *) die "Unknown argument: $1";;
  esac
done

[[ $EUID -eq 0 ]] || die "Must run as root (use sudo)."
[[ -n "$PANEL_URL" ]] || die "--panel-url is required."
[[ -n "$NODE_TOKEN" ]] || die "--token is required."

# ---- detect distro & arch ---------------------------------------------------
. /etc/os-release || die "Cannot read /etc/os-release."
log "Detected: ${PRETTY_NAME:-$ID}"
case "$ID" in
  ubuntu|debian) PKG="apt";;
  almalinux|rocky|rhel|centos) PKG="dnf";;
  *) warn "Untested distro '$ID' — continuing best-effort."; PKG="dnf";;
esac

ARCH="$(uname -m)"
case "$ARCH" in
  x86_64|amd64) GOARCH="amd64";;
  aarch64|arm64) GOARCH="arm64";;
  *) die "Unsupported architecture: $ARCH";;
esac

# ---- install Docker (unless skipped / present) ------------------------------
install_docker() {
  if command -v docker >/dev/null 2>&1; then
    log "Docker already installed: $(docker --version)"
    return
  fi
  [[ "$SKIP_DOCKER" == "true" ]] && { warn "Skipping Docker install (--skip-docker)."; return; }
  log "Installing Docker Engine..."
  curl -fsSL https://get.docker.com | sh
  systemctl enable --now docker
}
install_docker

# ---- create user & directories ----------------------------------------------
if ! id -u "$RUN_USER" >/dev/null 2>&1; then
  log "Creating system user '$RUN_USER'"
  useradd --system --home-dir "$DATA_DIR" --shell /usr/sbin/nologin "$RUN_USER"
fi
# Allow the agent to talk to the Docker socket.
if getent group docker >/dev/null 2>&1; then
  usermod -aG docker "$RUN_USER"
fi
install -d -o "$RUN_USER" -g "$RUN_USER" -m 0750 "$DATA_DIR" "$DATA_DIR/servers" "$DATA_DIR/backups"
install -d -m 0750 "$CONFIG_DIR"

# ---- download the agent binary ----------------------------------------------
BIN_NAME="refx-agent-linux-${GOARCH}"
if [[ "$AGENT_VERSION" == "latest" ]]; then
  DL_URL="https://github.com/${REPO}/releases/latest/download/${BIN_NAME}"
else
  DL_URL="https://github.com/${REPO}/releases/download/${AGENT_VERSION}/${BIN_NAME}"
fi
log "Downloading agent: $DL_URL"
TMP="$(mktemp)"
curl -fSL "$DL_URL" -o "$TMP" || die "Download failed. Build locally with 'make' in apps/node-agent if no release exists yet."
# Verify checksum if published alongside.
if curl -fsSL "${DL_URL}.sha256" -o "${TMP}.sha256" 2>/dev/null; then
  (cd "$(dirname "$TMP")" && echo "$(cut -d' ' -f1 "${TMP}.sha256")  $(basename "$TMP")" | sha256sum -c -) \
    || die "Checksum verification failed."
  log "Checksum verified."
fi
install -m 0755 "$TMP" "${INSTALL_DIR}/refx-agent"
rm -f "$TMP" "${TMP}.sha256"

# ---- write config -----------------------------------------------------------
log "Writing ${CONFIG_DIR}/config.yaml"
umask 077
cat > "${CONFIG_DIR}/config.yaml" <<EOF
# ReFx node-agent configuration (generated by install-node.sh)
panel_url: "${PANEL_URL}"
node_token: "${NODE_TOKEN}"
data_dir: "${DATA_DIR}"
api:
  bind: "0.0.0.0:8443"
  # On first start the agent self-signs a TLS cert; replace with a real one in prod.
sftp:
  bind: "0.0.0.0:2022"
log_level: "info"
EOF
chown "$RUN_USER:$RUN_USER" "${CONFIG_DIR}/config.yaml"
chmod 0600 "${CONFIG_DIR}/config.yaml"

# ---- firewall (best effort) -------------------------------------------------
if command -v ufw >/dev/null 2>&1; then
  ufw allow 8443/tcp || true
  ufw allow 2022/tcp || true
elif command -v firewall-cmd >/dev/null 2>&1; then
  firewall-cmd --permanent --add-port=8443/tcp || true
  firewall-cmd --permanent --add-port=2022/tcp || true
  firewall-cmd --reload || true
fi

# ---- systemd unit -----------------------------------------------------------
log "Installing systemd unit"
install -m 0644 "$(dirname "$0")/refx-agent.service" /etc/systemd/system/refx-agent.service 2>/dev/null || \
cat > /etc/systemd/system/refx-agent.service <<'EOF'
[Unit]
Description=ReFx Hosting node agent
After=network-online.target docker.service
Wants=network-online.target

[Service]
Type=simple
User=refx
Group=refx
ExecStart=/usr/local/bin/refx-agent --config /etc/refx/config.yaml
Restart=on-failure
RestartSec=5
LimitNOFILE=1048576
AmbientCapabilities=CAP_NET_BIND_SERVICE
NoNewPrivileges=true

[Install]
WantedBy=multi-user.target
EOF

systemctl daemon-reload
systemctl enable --now refx-agent

log "Agent installed and started. It will now register with the panel."
log "Check status:  systemctl status refx-agent"
log "Follow logs:   journalctl -u refx-agent -f"
